### ISSUE TITLE
Iosevka major release v28

### ISSUE THREAD

**Issue by DamienCassou** [protesilaos/iosevka-comfy#12]
Iosevka v28 has been released. Is it time to update iosevka-comfy accordingly?

**Comment by protesilaos** [comment]
> From: Damien Cassou ***@***.***>
> Date: Mon, 29 Jan 2024 23:49:11 -0800
>
> Iosevka v28 has been released. Is it time to update iosevka-comfy accordingly?

Before doing that, I need to find a way to manage this Git repo. The
files are large and each commit makes everything more cumbersome. I am
not sure what the best option is here. Suggestions are welcome.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by DamienCassou** [comment]
What about Git LFS? It is supported by github and gitlab. I've never tried it though.

**Comment by protesilaos** [comment]
I am pushing now with Git LFS. This is still not the next release. That will take some more time because upstream has made lots of breaking changes.

**Comment by nsemrau** [comment]
The documentation of Git LFS is a bit too opaque for me, so I am not entirely sure if you already meant exactly this in https://github.com/protesilaos/iosevka-comfy/issues/12#issuecomment-1936933856. I also saw https://github.com/protesilaos/iosevka-comfy/commit/9850b5320ecb460399bf3d007a95aff18628b13e. So please excuse me if this post is superflouous.

In case you did not meant this: Maybe only distribute the README/LICENCE and build plan file in the repository and set up the Release pipeline in [GitHub](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) and/or [GitLab](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)?

That would make the repo quite lean and manageable. Or do you explicitly want to distribute the font files via the repo, so that people can access the TTFs via cloning the repo - instead of through downloading the files from a "Releases" tab on a software forge through their browser?

**Comment by protesilaos** [comment]
> From: Nicolas Semrau ***@***.***>
> Date: Sun, 17 Mar 2024 09:09:05 -0700
>
> The documentation of Git LFS is a bit too opaque for me, so I am not
> entirely sure if you already meant exactly this in
> https://github.com/protesilaos/iosevka-comfy/issues/12#issuecomment-1936933856.
>
> In case you did not exactly: Maybe only distribute the README and
> build plan file in the repo and set up the Release pipeline in
> [GitHub](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)
> and/or
> [GitLab](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)?
>
> That would make the repo quite lean and manageable. Or do you
> explicitly want to distribute the font files via the repo, so that
> people can access the TTFs via cloning the repo - instead of through
> downloading the files from a "Releases" tab on a software forge
> through their browser?

My understanding of Git LFS is that it does not track the large files
directly, but only pointers to them. So this should be lighter. But I do
not know how this affects existing history.

About the build pipeline, I am happy to do that but I need to read how
to. There is always so much to learn!

At any rate, Iosevka has a new release. There are lots of breaking
changes, as usual. I need to resolve those and build/test all the
variants locally before doing anything with the repo.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I am pushing a new version now. It seems to be slow though, so I have no idea what Git LFS is supposed to do here. Maybe I need to rewrite history so that TFF files are no longer tracked... Next time.
