### ISSUE TITLE
Why won't upstream take the changes?

### ISSUE THREAD

**Issue by lf94** [protesilaos/iosevka-comfy#20]
If the changes are objectively better, what gives? :)

**Comment by protesilaos** [comment]
> From: 49fl ***@***.***>
> Date: Wed, 23 Oct 2024 20:57:42 -0700
>
> If the changes are objectively better, what gives? :)

Let's keep our beautiful fonts a secret between you and me. 🙃

On a serious note, the reason is that (i) I have not tried to contact
upstream about this because (ii) I am not sure it is needed. Also, this
separation makes it easier for me to maintain the desired style.

Iosevka provides a nice platform to build on and I am very happy with
what they are doing. My work here is tiny compared to their own.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by lf94** [comment]
You should try! I think they would appreciate it. I'm not even sure "style" is the right word here. I think the font is objectively better due to your design reasoning.

I super appreciate your work on this modification regardless. <3
